### ISSUE TITLE
Copy the code from Chapter 6 to Google Colab notebook

### ISSUE THREAD

**Issue by irudnyts** [trye-io/pyua#2]
You can copy the code either manually or using the following script [https://stackoverflow.com/questions/54796421/rmarkdown-knitrpurl-on-python-code-chunk](https://stackoverflow.com/questions/54796421/rmarkdown-knitrpurl-on-python-code-chunk). 

Please copy each chunk into a separate cell of the notebook. 

Here is the link to the dedicated Goolge Colab notebook: [https://colab.research.google.com/drive/1hgDqWJiXrM-d8BF8QZDU9xzWx7haIxA2?usp=sharing](https://colab.research.google.com/drive/1hgDqWJiXrM-d8BF8QZDU9xzWx7haIxA2?usp=sharing) (I have granted you write access).

**Comment by kkhmilovska** [comment]
Chapter 4: https://colab.research.google.com/drive/11qj9yGvFT8OU2gJwnUvveXiJwTsRWTMf?usp=sharing
Chapter 5: https://colab.research.google.com/drive/1Ac3l7X8bdNEl8FkQBLIPgmlLHIzUKPRm?usp=sharing
Chapter 6: https://colab.research.google.com/drive/1StQnIt-ykmzunPCT92mUpvS8GAJ68YIt?usp=sharing
