### ISSUE TITLE
Create exercises for Chapter 6

### ISSUE THREAD

**Issue by irudnyts** [trye-io/pyua#3]
You can get inspiration on types of exercises from this book: [https://teachtogether.tech/en/index.html#s:exercises](https://teachtogether.tech/en/index.html#s:exercises). 

Ideally, there should be three levels: A (easy), B (medium), and C (hard).

Ideally, exercises should be linked to real-world problems (like how to divide two apples into three parts...) rather than being purely theoretical. 

Here is [the link to the Google Forms](https://docs.google.com/forms/d/e/1FAIpQLScqt0AqAlaNNzoCwBZX1WvXySX2msbRPOJqzeMlxBTt_EObMw/viewform?usp=sharing). Please feel free to modify its appearance.

**Comment by kkhmilovska** [comment]
Chapter 6: https://docs.google.com/forms/d/e/1FAIpQLSebWsEjz4fOa2bMGGWjt0b1D-_3Klr7dS3-LZ41ISRBBzmSJQ/viewform?usp=sharing
